import {useEffect,useMemo,useState} from 'react'
import './styles.css'

const BASE=(import.meta.env.BASE_URL||'/').replace(/\/$/,'')
const pages={
  '/':'home','/product':'product','/student':'student','/teacher':'teacher','/ai-harness':'harness','/learning-evidence':'evidence','/solutions':'solutions','/trust':'trust','/platform':'platform','/customers':'customers','/pricing':'pricing','/about':'about','/login':'login','/register':'register'
}
const pathOf=key=>Object.entries(pages).find(([,v])=>v===key)?.[0]||'/'
const normalizedPath=()=>{let p=location.pathname;if(BASE&&p.startsWith(BASE))p=p.slice(BASE.length)||'/';return p}

const studentCaps=[
 ['Today / Next Step','基于 learner state 与当前任务，呈现此刻最值得完成的学习行动。'],['Courses','课程不是内容仓库，而是学习目标、任务、知识节点与证据的组织入口。'],['Tasks','把教师意图与学生执行连接起来，任务完成后继续进入证据与掌握度闭环。'],['Learning Session','在真实学习会话里完成尝试、求助、反馈与再尝试，而不是只进行聊天。'],['Ask Veya','提供分级帮助和解释，目标是帮助理解，不替学生直接完成学习任务。'],['Challenge / Discover','通过探索和挑战延伸学习，在新的尝试中形成更多可验证学习证据。'],['Learning Map','把知识节点、掌握状态与下一步学习方向可视化。'],['Learning Evidence','记录学习过程中真实发生的可追溯证据，为 learner model 与后续行动提供依据。']
]
const teacherCaps=[
 ['Command Center','集中呈现今日教学、班级注意事项、学生风险和待处理教学动作。'],['Student Insight','查看学生 learner model、学习证据、误区与学习上下文，而不是只看单一分数。'],['Learner Model','从持续 evidence 中形成可解释的学生学习状态，支持教师判断。'],['Evidence Review','教师能够审核、确认或失效证据，重要学习事实不由模型凭空写入。'],['Intervention','从问题发现进入教师干预、学生执行、follow-up evidence 与再次验证。'],['Teaching Policy','教师定义 AI 的教学边界、帮助方式与行为策略，让 AI 与教学目标对齐。'],['Content Studio','围绕真实教学流程组织内容，而不是生成后即结束。'],['Task Workspace','创建和管理教学任务，并持续跟踪学生执行与后续证据。'],['Class Management','班级、学生与教学上下文进入统一控制面。'],['Pilot Results','把试点、学习结果和闭环证据汇总到可复盘结果视图。']
]
const advantages=[['Evidence-first','AI 可以解释和推荐，但重要学习事实必须来自 Evidence。'],['Teacher in control','教师可以审核证据、调整策略、发起干预并决定教学边界。'],['Closed-loop learning','从学习行动到下一步，不在“AI 给出建议”处结束。'],['Student + Teacher','学生学习 OS 与教师控制面共享同一份真实学习上下文。'],['Governed Harness','模型、Skills、Tools 通过 Harness 和 Policy 进入教育工作流。'],['Provider-neutral','产品价值不依赖某一个模型品牌，为模型升级和多模型路由留出空间。']]
const solutionGroups=[['K12 学校','连接日常教学、学生学习、证据和教师干预，让 AI 真正进入学校工作流。'],['高校与职业教育','围绕课程目标、学习过程与能力证据建立持续学习闭环。'],['教育机构','用统一的学生学习上下文和教师控制面承载规模化个性化教学。'],['教师团队','把 AI 从零散工具变成受教学策略约束、可复盘的工作伙伴。']]

function useTheme(){const [mode,setMode]=useState(()=>localStorage.getItem('veya-theme')||'auto');const [tick,setTick]=useState(0);useEffect(()=>{if(mode!=='auto')return;const id=setInterval(()=>setTick(v=>v+1),60000);return()=>clearInterval(id)},[mode]);const resolved=useMemo(()=>mode==='auto'?((new Date().getHours()>=7&&new Date().getHours()<19)?'light':'dark'):mode,[mode,tick]);useEffect(()=>{document.documentElement.dataset.theme=resolved;localStorage.setItem('veya-theme',mode)},[mode,resolved]);return{mode,setMode,resolved}}
function useRouter(){const read=()=>pages[normalizedPath()]||'home';const [page,setPageState]=useState(read);useEffect(()=>{const fn=()=>setPageState(read());addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);const go=key=>{const p=pathOf(key);history.pushState({},'',`${BASE}${p==='/'?'/':p}`);setPageState(key);window.scrollTo({top:0,behavior:'smooth'})};return{page,go}}

const Icon=({children})=><span className="icon">{children}</span>
const Button=({children,onClick,secondary=false,ghost=false})=><button className={`btn ${secondary?'secondary':''} ${ghost?'ghost':''}`} onClick={onClick}>{children}</button>
const SectionTitle=({eyebrow,title,copy,center=false})=><div className={`section-title ${center?'center':''}`}><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>
const CapabilityGrid=({items})=><div className="cap-grid">{items.map(([title,copy],i)=><article className="cap-card" key={title}><Icon>{String(i+1).padStart(2,'0')}</Icon><h3>{title}</h3><p>{copy}</p></article>)}</div>
function ProductShot({name,src,portrait=false}){const [ok,setOk]=useState(true);return <figure className={`product-shot ${portrait?'portrait':''}`}>{ok?<img src={`${BASE}${src}`} alt={`Veya 真实产品截图：${name}`} onError={()=>setOk(false)}/>:<div className="shot-missing"><b>{name}</b><span>仅接受 Veya live-runtime / verified snapshot</span><small>当前仓库尚未同步该截图二进制，禁止使用概念图替代。</small></div>}<figcaption><span>●</span> Verified Veya product · {name}</figcaption></figure>}

function Header({page,go,theme}){const [open,setOpen]=useState(false);const nav=[['product','产品'],['student','学生端'],['teacher','教师端'],['solutions','解决方案'],['pricing','合作'],['about','关于']];return <header className="site-header"><div className="nav-shell"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">V</span><strong>Veya</strong></button><nav className={open?'open':''}>{nav.map(([k,l])=><button key={k} className={page===k?'active':''} onClick={()=>{go(k);setOpen(false)}}>{l}</button>)}</nav><div className="header-actions"><div className="theme"><button className={theme.mode==='auto'?'on':''} onClick={()=>theme.setMode('auto')} title="按本地时间自动切换">◐<span>自动</span></button><button className={theme.mode==='light'?'on':''} onClick={()=>theme.setMode('light')} title="浅色">☀</button><button className={theme.mode==='dark'?'on':''} onClick={()=>theme.setMode('dark')} title="深色">☾</button></div><Button ghost onClick={()=>go('login')}>登录</Button><Button onClick={()=>go('register')}>注册</Button><button className="menu" onClick={()=>setOpen(v=>!v)} aria-label="菜单">{open?'×':'☰'}</button></div></div></header>}
function Footer({go}){return <footer><div className="footer-grid"><div><div className="brand static"><span className="brand-mark">V</span><strong>Veya</strong></div><p>AI-native Teaching & Learning OS<br/>让每个学习旅程被看见、被理解、被支持。</p></div><div><b>产品</b><button onClick={()=>go('student')}>学生端</button><button onClick={()=>go('teacher')}>教师端</button><button onClick={()=>go('harness')}>AI Harness</button><button onClick={()=>go('evidence')}>Learning Evidence</button></div><div><b>组织</b><button onClick={()=>go('solutions')}>解决方案</button><button onClick={()=>go('trust')}>安全与隐私</button><button onClick={()=>go('platform')}>平台与集成</button><button onClick={()=>go('customers')}>Pilot 与成果</button></div><div><b>Veya</b><button onClick={()=>go('pricing')}>合作</button><button onClick={()=>go('about')}>关于</button><button onClick={()=>go('login')}>登录</button><button onClick={()=>go('register')}>注册</button></div></div><div className="footer-bottom"><span>© 2026 Veya</span><span>Learning, understood.</span></div></footer>}
const CTA=({go})=><section className="cta"><span className="kicker">START WITH REAL LEARNING</span><h2>让 AI 服务学习，而不是绕开学习。</h2><p>从学生每一次尝试，到教师每一次判断，Veya 把证据、行动和结果连接起来。</p><div><Button onClick={()=>go('register')}>开始体验 →</Button><Button secondary onClick={()=>go('pricing')}>联系 Veya</Button></div></section>
const PageHero=({eyebrow,title,copy,children})=><section className="page-hero"><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{copy}</p>{children}</section>

function Home({go}){return <><main><section className="home-hero"><div className="hero-copy"><span className="kicker">AI-NATIVE TEACHING & LEARNING OS</span><h1>让每个学习旅程<br/><em>被看见、被理解、被支持</em></h1><p>Veya 基于真实学习证据连接学生学习、教师教学与 AI。不是又一个 AI 工具箱，而是一套持续运行的 Teaching & Learning OS。</p><div className="hero-actions"><Button onClick={()=>go('register')}>开始体验 →</Button><Button secondary onClick={()=>go('product')}>了解 Veya</Button></div><div className="truth">✓ 官网产品画面只接受 Veya 真实运行截图，绝不使用虚构 Dashboard。</div></div><div className="hero-visual"><ProductShot name="教师端 · Command Center" src="/product-shots/teacher-home.png"/><ProductShot name="学生端 · Today" src="/product-shots/student-h5-home.png" portrait/></div></section><section className="trust-strip"><span>Evidence-first</span><span>Teacher in control</span><span>Closed loop</span><span>Student + Teacher</span><span>Governed Harness</span></section><section className="duo"><div><SectionTitle eyebrow="FOR STUDENTS" title="Learning Life OS" copy="从今天该做什么，到真实学习、求助、证据与下一步，学生拥有连续而清晰的学习旅程。"/><CapabilityGrid items={studentCaps.slice(0,4)}/><Button secondary onClick={()=>go('student')}>查看学生端 →</Button></div><ProductShot name="学生端 · Today / Next Step" src="/product-shots/student-home.png"/></section><section className="duo reverse"><ProductShot name="教师端 · 今日教学" src="/product-shots/teacher-home.png"/><div><SectionTitle eyebrow="FOR TEACHERS" title="Teacher Control Plane" copy="从发现问题、理解原因、审核证据，到干预与再次验证，教师始终掌握教学判断。"/><CapabilityGrid items={teacherCaps.slice(0,4)}/><Button secondary onClick={()=>go('teacher')}>查看教师端 →</Button></div></section><section className="harness-section"><SectionTitle eyebrow="VEYA AI HARNESS" title="把模型能力变成受治理的教育能力" copy="Models、Skills、Tools 不直接冲进课堂，而是通过 Harness、Teaching Policy、Evidence 和教师控制进入真实学习闭环。" center/><div className="flow">{['Models','Skills','Tools','Harness','Policy','Evidence','Next Action'].map((x,i)=><div key={x}><small>{String(i+1).padStart(2,'0')}</small><b>{x}</b></div>)}</div><Button secondary onClick={()=>go('harness')}>了解 Harness →</Button></section><section><SectionTitle eyebrow="WHY VEYA" title="竞争力不在功能数量，而在闭环质量" copy="Veya 不追求堆出几十个 AI 按钮，而是把真实学习事实、教师主导和连续行动做成基础设施。" center/><div className="adv-grid">{advantages.map(([a,b])=><article key={a}><Icon>✓</Icon><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main></>}
function Product({go}){return <main><PageHero eyebrow="PRODUCT" title={<>一套系统，连接<span>学习、教学与 AI</span></>} copy="Student Learning Life OS、Teacher Control Plane、Learning Evidence 与 AI Harness 不是四个孤岛，而是同一个教育闭环的不同控制面。"><div className="hero-actions"><Button onClick={()=>go('student')}>学生端</Button><Button secondary onClick={()=>go('teacher')}>教师端</Button></div></PageHero><section><SectionTitle eyebrow="PRODUCT MAP" title="Veya 产品全貌" copy="学生执行学习，Evidence 记录事实，Learner Model 汇总状态，教师通过 Control Plane 决策，Harness 在 Policy 约束下提供智能。"/><div className="architecture"><div>Student<br/><b>Learning Life OS</b></div><span>→</span><div>Learning<br/><b>Evidence</b></div><span>→</span><div>Learner<br/><b>Model</b></div><span>→</span><div>Teacher<br/><b>Control Plane</b></div><span>↔</span><div>Governed<br/><b>AI Harness</b></div></div></section><section><SectionTitle eyebrow="SHIPPED CAPABILITIES" title="当前真实可使用能力" copy="官网只呈现已经进入产品工作流的能力，不把 roadmap 写成已发布。"/><div className="two-columns"><div><h3>学生端</h3><CapabilityGrid items={studentCaps}/></div><div><h3>教师端</h3><CapabilityGrid items={teacherCaps}/></div></div></section><CTA go={go}/></main>}
function Student({go}){return <main><PageHero eyebrow="STUDENT · LEARNING LIFE OS" title={<>学习不是交作业，<span>而是一段可理解的旅程。</span></>} copy="Veya 把 Today、Courses、Tasks、Learning Session、Ask Veya、Challenge、Learning Map 与 Learning Evidence 连成连续学习体验。"/><section className="shot-gallery"><ProductShot name="Today / Next Step" src="/product-shots/student-home.png"/><ProductShot name="Learning Session" src="/product-shots/student-session.png"/><ProductShot name="Ask Veya" src="/product-shots/student-ask.png"/><ProductShot name="Learning Map" src="/product-shots/student-map.png"/></section><section><SectionTitle eyebrow="STUDENT CAPABILITIES" title="学生端完整能力" copy="每个入口都服务于真实学习状态，而不是互不相干的 AI 小工具。"/><CapabilityGrid items={studentCaps}/></section><section className="journey"><SectionTitle eyebrow="LEARNING JOURNEY" title="从下一步，到下一次成长"/><div className="journey-line">{['Today','Task / Session','Ask / Challenge','Evidence','Learner State','Learning Map','Next Action'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></section><CTA go={go}/></main>}
function Teacher({go}){return <main><PageHero eyebrow="TEACHER · CONTROL PLANE" title={<>AI 提供能力，<span>教师掌握教学。</span></>} copy="教师看到的不只是分数，而是学生是谁、为什么卡住、证据是什么、下一步应该做什么，以及干预之后是否真正改善。"/><section className="shot-gallery"><ProductShot name="Command Center" src="/product-shots/teacher-home.png"/><ProductShot name="Student Insight" src="/product-shots/teacher-insight.png"/><ProductShot name="Evidence Review" src="/product-shots/teacher-evidence.png"/><ProductShot name="Teaching Policy" src="/product-shots/teacher-policy.png"/></section><section><SectionTitle eyebrow="TEACHER CAPABILITIES" title="教师端完整能力" copy="把注意力、洞察、证据、策略、内容、任务、管理与结果放在同一个控制面。"/><CapabilityGrid items={teacherCaps}/></section><section className="journey"><SectionTitle eyebrow="TEACHING LOOP" title="从发现问题，到验证干预结果"/><div className="journey-line">{['Attention','Evidence','Misconception','Next Action','Teacher Review','Intervention','Follow-up Evidence','Outcome'].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></section><CTA go={go}/></main>}
function Harness({go}){return <main><PageHero eyebrow="AI HARNESS" title={<>AI 不直接接管教育，<span>它被教育目标约束。</span></>} copy="Veya Harness 负责把模型、Skills、Tools、教学策略、学习上下文与证据组合成可治理的运行上下文。"/><section><SectionTitle eyebrow="RUNTIME FLOW" title="从模型能力到教学行动"/><div className="architecture large"><div>Models<br/><b>多模型输入</b></div><span>→</span><div>Skills<br/><b>教育能力</b></div><span>→</span><div>Tools<br/><b>真实工具</b></div><span>→</span><div>Harness<br/><b>上下文与治理</b></div><span>→</span><div>Policy<br/><b>教学边界</b></div><span>→</span><div>Evidence<br/><b>事实约束</b></div></div></section><section><SectionTitle eyebrow="DESIGN PRINCIPLES" title="Harness 的教育原则"/><div className="adv-grid">{[['Policy before autonomy','模型能力越强，越需要明确教学边界。'],['Evidence before state','AI 的判断不能直接成为学生掌握事实。'],['Teacher override','教师能够审核、修改、失效和干预。'],['Context-aware','每次运行结合课程、任务、学生状态与当前会话。'],['Tool-governed','工具调用不是裸奔，必须经过能力解析与策略。'],['Model-neutral','支持未来模型升级，而不重写上层教育工作流。']].map(([a,b])=><article key={a}><Icon>◎</Icon><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main>}
function Evidence({go}){return <main><PageHero eyebrow="LEARNING EVIDENCE" title={<>不是 AI 觉得你学会了，<span>而是证据证明你学会了。</span></>} copy="Evidence 是 Veya 最重要的产品边界之一。学习活动形成可追溯事实，再进入 learner model、教学判断与下一步行动。"/><section className="evidence-flow"><div><b>01</b><h3>Learning Activity</h3><p>任务、会话、挑战、回答与重新尝试。</p></div><div><b>02</b><h3>Evidence</h3><p>把发生过什么记录成可追溯学习事实。</p></div><div><b>03</b><h3>Learner State</h3><p>综合证据形成可解释状态，而不是模型随口判断。</p></div><div><b>04</b><h3>Next Action</h3><p>面向学生与教师生成下一步可执行行动。</p></div><div><b>05</b><h3>Reverification</h3><p>干预后重新采集 evidence，验证是否真的改善。</p></div></section><section><SectionTitle eyebrow="WHY IT MATTERS" title="Evidence 让 AI 教育从“看起来聪明”走向“可以负责”"/><div className="adv-grid">{[['可追溯','知道一个判断来自哪些学习行为与证据。'],['可审核','教师可以确认、否定或失效不可靠证据。'],['可解释','Learner Model 的变化能够回到 evidence。'],['可验证','干预之后通过新的 evidence 判断效果。'],['可治理','AI 不直接制造关键学习事实。'],['可积累','跨学习会话形成持续学习历史。']].map(([a,b])=><article key={a}><Icon>✓</Icon><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main>}
function Solutions({go}){return <main><PageHero eyebrow="SOLUTIONS" title={<>不是买一个 AI 按钮，<span>而是建立学习闭环。</span></>} copy="Veya 面向学校、教师团队与教育组织，把 AI 能力嵌入已有教学目标与真实学习过程。"/><section><SectionTitle eyebrow="WHO VEYA SERVES" title="围绕不同教育组织进入真实工作流"/><div className="solution-grid">{solutionGroups.map(([a,b],i)=><article key={a}><Icon>{i+1}</Icon><h3>{a}</h3><p>{b}</p><button onClick={()=>go(i===3?'teacher':'pricing')}>了解更多 →</button></article>)}</div></section><section className="dark-panel"><SectionTitle eyebrow="DEPLOYMENT PRINCIPLE" title="先从一个真实闭环开始，再逐步扩展" copy="选择一个课程或班级，从学生学习、Evidence、教师干预与结果复核开始，而不是一开始部署几十个 AI 工具。"/></section><CTA go={go}/></main>}
function Trust({go}){return <main><PageHero eyebrow="TRUST · SAFETY · GOVERNANCE" title={<>教育 AI 的能力，<span>必须伴随边界。</span></>} copy="Veya 把租户隔离、身份权限、Evidence 审核、Teaching Policy、审计与教师控制视为产品能力，而不是发布后的补丁。"/><section><div className="adv-grid">{[['Identity & Tenant','身份、角色和租户范围进入请求上下文，跨租户能力默认 fail-closed。'],['Teacher control','教师保留 Evidence Review、Policy 与 Intervention 的最终控制。'],['Evidence integrity','关键学习状态不允许由模型直接写入。'],['Auditability','重要能力围绕真实状态和可追踪动作设计。'],['Privacy by design','尽量减少不必要的数据扩散，让教育上下文在明确范围内流动。'],['No fake capability','官网与产品均不以不可用菜单、概念 UI 冒充真实能力。']].map(([a,b])=><article key={a}><Icon>▣</Icon><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main>}
function Platform({go}){return <main><PageHero eyebrow="PLATFORM & INTEGRATION" title={<>连接模型、能力与教育系统，<span>不把自己锁死。</span></>} copy="Veya 以 provider-neutral 思路组织模型、Skills、Tools、MCP 与外部教育系统连接，让上层学习闭环保持稳定。"/><section><SectionTitle eyebrow="CAPABILITY CENTER" title="模型之外，还有 Skills、Agents、Tools 与 MCP" copy="教师与学生使用的是教育能力，底层可以由不同运行时和连接方式承载。"/><div className="platform-grid">{[['Models','配置和选择适合的模型能力。'],['Skills','把可复用教育方法封装成能力。'],['Agents','围绕明确角色组织持续工作。'],['Tools','连接真实数据与执行能力。'],['MCP','以标准协议扩展外部工具与资源。'],['Integrations','面向学校现有平台与通信渠道逐步连接。']].map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main>}
function Customers({go}){return <main><PageHero eyebrow="PILOT & OUTCOMES" title={<>先证明学习闭环，<span>再谈规模化。</span></>} copy="Veya 的 Pilot 关注学习证据、教师行动、再次验证与真实结果，而不是只统计 AI 调用了多少次。"/><section><div className="metrics"><div><strong>Evidence</strong><span>学习事实是否持续产生</span></div><div><strong>Action</strong><span>学生和教师是否获得可执行下一步</span></div><div><strong>Intervention</strong><span>教师干预是否真正进入工作流</span></div><div><strong>Outcome</strong><span>后续证据是否证明改善</span></div></div></section><section><SectionTitle eyebrow="CASE STUDY POLICY" title="官网不伪造客户背书" copy="在真实学校案例获得明确授权前，Veya 不使用虚构学校 Logo、虚构教师头像或虚构评价。这里保留正式案例结构，但不会用假案例填空。"/></section><CTA go={go}/></main>}
function Pricing({go}){return <main><PageHero eyebrow="WORK WITH VEYA" title={<>从一个真实教学闭环开始。</>} copy="现阶段采用合作 / Pilot 模式，根据学校、班级、课程和集成范围确定实施方案，不发布未经验证的虚假价格档位。"/><section className="pricing-cards"><article><span>PILOT</span><h3>学校 / 教师团队试点</h3><p>选择真实课程和班级，完成学生学习、Evidence、教师干预与结果复核。</p><ul><li>学生 Learning Life OS</li><li>教师 Control Plane</li><li>Evidence & Learner Model</li><li>AI Harness / Teaching Policy</li><li>Pilot Results</li></ul><Button onClick={()=>go('register')}>申请 Pilot</Button></article><article><span>PLATFORM</span><h3>教育组织与平台合作</h3><p>面向更大范围部署、模型与能力接入、组织治理和平台集成。</p><ul><li>多组织 / 租户治理</li><li>模型与 Capability Center</li><li>Skills / Tools / MCP</li><li>平台集成规划</li><li>长期产品共创</li></ul><Button secondary onClick={()=>go('register')}>联系我们</Button></article></section></main>}
function About({go}){return <main><PageHero eyebrow="ABOUT VEYA" title={<>我们想解决的不是“怎么用 AI”，<span>而是“怎么让学习真正发生”。</span></>} copy="Veya 从 Learning Evidence、教师控制与持续学习上下文出发，构建 AI-native Teaching & Learning OS。"/><section className="manifesto"><p>教育不缺更多生成内容的按钮。</p><p>真正困难的是知道学生现在会什么、不会什么、为什么卡住，以及接下来什么行动最值得做。</p><p>同样困难的是让教师在 AI 时代仍然拥有教学判断、边界和责任。</p><p>Veya 因此把 Evidence、Learner Model、Teaching Policy、Intervention 与 AI Harness 放在同一个系统里。</p></section><section><SectionTitle eyebrow="PRODUCT PRINCIPLES" title="Veya 坚持的几件事"/><div className="adv-grid">{advantages.map(([a,b])=><article key={a}><Icon>V</Icon><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA go={go}/></main>}
function Auth({mode,go}){const register=mode==='register';return <main className="auth-page"><section className="auth-card"><div className="auth-copy"><span className="brand-mark big">V</span><span className="kicker">VEYA ACCOUNT</span><h1>{register?'创建 Veya 账户':'欢迎回来'}</h1><p>{register?'开始你的 Veya 学习与教学旅程。':'登录学生端或教师端，继续真实学习闭环。'}</p><div className="auth-note"><b>当前状态</b><span>官网入口已完成。正式认证将连接 Veya 产品 Auth API，在 API 接通前不会伪造“登录成功”。</span></div></div><form onSubmit={e=>e.preventDefault()}><label>邮箱 / 账号<input type="text" placeholder="name@example.com"/></label>{register&&<label>姓名<input type="text" placeholder="你的名字"/></label>}<label>密码<input type="password" placeholder="••••••••"/></label>{register&&<label>身份<select defaultValue="student"><option value="student">学生</option><option value="teacher">教师</option></select></label>}<Button>{register?'注册':'登录'}</Button><p className="switch-auth">{register?'已有账户？':'还没有账户？'} <button type="button" onClick={()=>go(register?'login':'register')}>{register?'登录':'注册'}</button></p></form></section></main>}

export default function App(){const theme=useTheme();const {page,go}=useRouter();const content={home:<Home go={go}/>,product:<Product go={go}/>,student:<Student go={go}/>,teacher:<Teacher go={go}/>,harness:<Harness go={go}/>,evidence:<Evidence go={go}/>,solutions:<Solutions go={go}/>,trust:<Trust go={go}/>,platform:<Platform go={go}/>,customers:<Customers go={go}/>,pricing:<Pricing go={go}/>,about:<About go={go}/>,login:<Auth mode="login" go={go}/>,register:<Auth mode="register" go={go}/>}[page];return <><Header page={page} go={go} theme={theme}/>{content}<Footer go={go}/></>}
